### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/docs#16]

**Comment by Prajnaprabhu3** [comment]
hey @ferreiratiago , I would like to work on this

**Comment by ferreiratiago** [comment]
Hi @Prajnaprabhu3 Thanks for your help 🙏🏼  This particular issue, along with #17, is better for the team to do it. There's a lot of information in our heads that need to be write down. Does that make sense? We would love if you could pick the issue #18 😃

**Comment by Prajnaprabhu3** [comment]
yeah sure that makes sense, I would be more than willing to contribute to improvements, if any later on!
