### ISSUE TITLE
Fix `label-ship-show-ask` workflow and the related rules

### ISSUE THREAD

**Issue by shay2025** [reviewpad/docs#187]
**Describe the bug**
When an external pull request with the `ship label` is closed, Reviewpad runs again on the same pull request and adds the label `ask` which is wrong behavior.

**To Reproduce**
1. Open a pull request being a non-maintainer and select the `ship` strategy.

**Expected behavior**
Reviewpad should not add the `ask` label after being merged.

**Comment by fmallet** [comment]
For the time-being, this workflow and the support by Reviewpad of the SHIP/SHOW/ASK model is not anymore documented.
