### ISSUE TITLE
Clarify the `task check -f` in the pull request template

### ISSUE THREAD

**Issue by naomi-lgbt** [reviewpad/docs#24]
In the [pull request template](https://github.com/reviewpad/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), it is indicated that we need to run `task check -f`. However, running this threw a command not found error on my local clone.

It looks like this project is falling back to the `.github` pull request template, which means this checklist item might not be applicable? If so, it may be best to create a template specifically for this repo.

**Comment by ferreiratiago** [comment]
Hi @naomi-lgbt Thanks for this issue 🙏🏼 You're right. We need to create a better pull request template for the documentation. The fallback on `reviewpad/.github` is not appropriate for the documentation.
