### ISSUE TITLE
Add a architecture diagram

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/docs#39]
**Is your feature request related to a problem? Please describe.**
It would be great if we could have an architecture diagram in order to understand how we could use reviewpad within another cli what not GitHub actions.

**Comment by fmallet** [comment]
I'm closing this issue `won't fix` as I don't have a good understanding of the need. Feel free to reopen the issue @ferreiratiago and elaborate a bit more the description if you think it's worth it.
